site_name: UI Full Stack Project
copyright: Sudheer Reddy G

site_description: "My Project."

repo_url: https://github.com/SudheerKReddyG/ui.github.io
repo_name: SudheerKReddyG/ui.github.io

theme:
  icon:
    repo: fontawesome/brands/github
  name: "material"
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: "blue"
      accent: "grey"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: "black"
      accent: "white"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

extra:
  generator: false

nav:
    - Home: index.md
    - Softwares Installation(Setup): 
      - Installation/Notes.md
      - Installation/angular.md
      - Installation/java.md
      - Installation/editors.md
    - About: about.md

copyright: Copyright &copy; 2023 Sudheer Reddy G

